[program:send-incident-mail]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/logger/artisan queue:work redis --queue=sendMailJob --sleep=0
directory=/var/www/logger
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
numprocs=4
redirect_stderr=true
user=www
stdout_logfile=/var/log/supervisor/send-incident-mail-log.log
stdout_logfile_maxbytes=5MB
stopwaitsecs=3600
