[program:write-incident-log]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/logger/artisan queue:work --queue=writeIncidentLog --sleep=3 --daemon
directory=/var/www/logger
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
numprocs=1
redirect_stderr=true
user=www
stdout_logfile=/var/log/supervisor/write-incident-log.log
stdout_logfile_maxbytes=5MB
stopwaitsecs=3600